# Operators

## 1.Arithmetic operators
###### + - * / // %

a Write a Python expression to calculate the sum of two numbers.
b Create a program that calculates the product of three numbers using multiplication.
c Write a function that computes the difference between two numbers.
d Calculate the result of dividing one number by another (ensure to handle both integer and float divisions).
e Create a program that uses exponentiation to find the square of a number.
f Write a script that combines addition, subtraction, and multiplication in a single expression.
g Develop a function that calculates the remainder when dividing one number by another.
h Implement a program that uses parentheses to control the order of operations in a complex arithmetic expression

In [9]:
x=int(input('Enter a number : '))
y=int(input('Enter a number : '))

Enter a number :  1
Enter a number :  2


In [10]:
#a.Write a Python expression to calculate the sum of two numbers.
x+y

3

In [11]:
#b.Create a program that calculates the product of three numbers using multiplication.
z=int(input('Enter a number : '))
x*y*z

Enter a number :  3


6

In [12]:
#c.Write a function that computes the difference between two numbers
x-y

-1

In [13]:
#d. Calculate the result of dividing one number by another (ensure to handle both integer and float divisions).
x/y

0.5

In [14]:
# e. Create a program that uses exponentiation to find the square of a number.
x**2

1

In [15]:
# f. Write a script that combines addition, subtraction, and multiplication in a single expression.
x+y/2*2

3.0

In [20]:
#g. Develop a function that calculates the remainder when dividing one number by another.
def d(d):
    f=d%5
    print(f)
d(26)

1


In [21]:
#h Implement a program that uses parentheses to control the order of operations in a complex arithmetic expression
(x+y)/(2*z)

0.5

## 2. Relational Operators
###### <,>,<=,>=,==,!=

##### a. Relational operators will give boolean output while comparing LHS and RHS

In [22]:
10>20

False

## 3.Logical operators
###### and or not

##### a.Logical operators are used to compare two booleans

In [23]:
10>20 or 10==10

True

In [27]:
not 10==10

False

## 4. Bitwise operator
###### &-->bitwise and operator
###### |-->bitwise or operator

In [29]:
result = x & y
print(result)

0


In [30]:
bin(1)

'0b1'

In [31]:
bin(2)

'0b10'

In [32]:
bin(3)

'0b11'

## 5. Membership Operators
###### in notin

##### Membership operators in Python are used to check if a value is a member of a sequence such as a list, tuple, string, or dictionary

In [13]:
fruits = ["apple", "banana", "cherry"]
print("apple" in fruits)

True


In [1]:
L=['VIJAY','AJJAY']
'A' in L    ## It gives falls coz it can take a speparate 

False

#### What are Libraries
###### It's like a big box of special tools (functions and code) that other people have made.

#### What are data frames
###### dataframes are a specific way to organize and manipulate data within a programming environment. Eg Pandas

#### Funtion<module(Collection of Funtions)<package(Collection of Modules)<library(Collection of packages) 

##### How to import a funtion using module 

In [6]:
import math

# Example usage of math module
print(math.sqrt(16))  # Output: 4.0
print(math.pi)       # Output: 3.141592653589793


4.0
3.141592653589793


In [8]:
# Using the inbuilt function `len`
my_list = [1, 2, 3, 4, 5]
list_length = len(my_list)  # Inbuilt function
print(f"Length of my_list: {list_length}")  # Output: 5

# Using the inbuilt module `math`
import math

square_root = math.sqrt(16)  # Inbuilt module
print(f"Square root of 16: {square_root}")  # Output: 4.0

# Using the inbuilt package `collections`
from collections import Counter

my_list = [1, 2, 2, 3, 3, 3]
counter = Counter(my_list)  # Inbuilt package
print(f"Element counts in my_list: {counter}")  # Output: Counter({3: 3, 2: 2, 1: 1})

Length of my_list: 5
Square root of 16: 4.0
Element counts in my_list: Counter({3: 3, 2: 2, 1: 1})


In [1]:
import pandas as pd
import seaborn as sns

In [2]:
# Get the list of available dataset names in seaborn
dataset_names = sns.get_dataset_names()
print(dataset_names)

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic', 'anagrams', 'anagrams', 'anscombe', 'anscombe', 'attention', 'attention', 'brain_networks', 'brain_networks', 'car_crashes', 'car_crashes', 'diamonds', 'diamonds', 'dots', 'dots', 'dowjones', 'dowjones', 'exercise', 'exercise', 'flights', 'flights', 'fmri', 'fmri', 'geyser', 'geyser', 'glue', 'glue', 'healthexp', 'healthexp', 'iris', 'iris', 'mpg', 'mpg', 'penguins', 'penguins', 'planets', 'planets', 'seaice', 'seaice', 'taxis', 'taxis', 'tips', 'tips', 'titanic', 'titanic', 'anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']


In [17]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'conca

In [18]:
print(dir(sns))

['FacetGrid', 'JointGrid', 'PairGrid', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_compat', '_core', '_decorators', '_docstrings', '_oldcore', '_orig_rc_params', '_statistics', '_stats', 'algorithms', 'axes_style', 'axisgrid', 'barplot', 'blend_palette', 'boxenplot', 'boxplot', 'categorical', 'catplot', 'choose_colorbrewer_palette', 'choose_cubehelix_palette', 'choose_dark_palette', 'choose_diverging_palette', 'choose_light_palette', 'clustermap', 'cm', 'color_palette', 'colors', 'countplot', 'crayon_palette', 'crayons', 'cubehelix_palette', 'dark_palette', 'desaturate', 'despine', 'displot', 'distplot', 'distributions', 'diverging_palette', 'dogplot', 'ecdfplot', 'external', 'get_data_home', 'get_dataset_names', 'heatmap', 'histplot', 'hls_palette', 'husl_palette', 'jointplot', 'kdeplot', 'light_palette', 'lineplot', 'lmplot', 'load_dataset', 'matrix', 'miscplot', 'move_legend', 'mpl', 'mpl_pale

In [6]:
table=sns.load_dataset('titanic')
table

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

##### How to get top five rows?

In [39]:
table.head(25)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500        S   First   
12         0       3    male  20.0      0      0   8.0500        S   Third   
13         0       3    male  39.0      1      5  31.2750        S   Third   
14         0       3  female  14.0      0      0   7.8542        S   Third   
15         1       2  female  55.0      0      0  16.0000        S  Second   
16         0       3    male   2.0      4      1  29.1250        Q   Third   
17         1       2    male   NaN      0      0  13.0000        S  Second   
18         0       3  female  31.0      1      0  18.0000        S   Third   
19         1       3  female   NaN      0      0   7.2250        C   Third   
20         0       2    male  35.0      0      0  26.0000        S  Second   
21         1       2    male  34.0      0      0  13.0000        S  Second   
22         1       3  female  15.0      0      0   8.0292        Q   Third   
23         1       1    male  28.0      0      0  35.5000        S   First   
24         0       3  female   8.0      3      1  21.0750        S   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
1   woman       False    C    Cherbourg   yes  False  
2   woman       False  NaN  Southampton   yes   True  
3   woman       False    C  Southampton   yes  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
7   child       False  NaN  Southampton    no  False  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
12    man        True  NaN  Southampton    no   True  
13    man        True  NaN  Southampton    no  False  
14  child       False  NaN  Southampton    no   True  
15  woman       False  NaN  Southampton   yes   True  
16  child       False  NaN   Queenstown    no  False  
17    man        True  NaN  Southampton   yes   True  
18  woman       False  NaN  Southampton    no  False  
19  woman       False  NaN    Cherbourg   yes   True  
20    man        True  NaN  Southampton    no   True  
21    man        True    D  Southampton   yes   True  
22  child       False  NaN   Queenstown   yes   True  
23    man        True    A  Southampton   yes   True  
24  child       False  NaN  Southampton    no  False

##### How to get the no of rows and columns

In [32]:
table.shape           

(891, 15)

##### (How to get a structure of a formula or any syntex-----------Shift&tab)

##### Q1 .Get the records that represent children or people who are travelling for free

In [44]:
table[(table['who']=='child')|((table['who']=='man')&(table['fare']==0))|((table['who']=='women')&(table['fare']==0))]

survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
7           0       3    male   2.00      3      1  21.0750        S   Third   
9           1       2  female  14.00      1      0  30.0708        C  Second   
10          1       3  female   4.00      1      1  16.7000        S   Third   
14          0       3  female  14.00      0      0   7.8542        S   Third   
16          0       3    male   2.00      4      1  29.1250        Q   Third   
..        ...     ...     ...    ...    ...    ...      ...      ...     ...   
831         1       2    male   0.83      1      1  18.7500        S  Second   
850         0       3    male   4.00      4      2  31.2750        S   Third   
852         0       3  female   9.00      1      1  15.2458        C   Third   
869         1       3    male   4.00      1      1  11.1333        S   Third   
875         1       3  female  15.00      0      0   7.2250        C   Third   

       who  adult_male deck  embark_town alive  alone  
7    child       False  NaN  Southampton    no  False  
9    child       False  NaN    Cherbourg   yes  False  
10   child       False    G  Southampton   yes  False  
14   child       False  NaN  Southampton    no   True  
16   child       False  NaN   Queenstown    no  False  
..     ...         ...  ...          ...   ...    ...  
831  child       False  NaN  Southampton   yes  False  
850  child       False  NaN  Southampton    no  False  
852  child       False  NaN    Cherbourg    no  False  
869  child       False  NaN  Southampton   yes  False  
875  child       False  NaN    Cherbourg   yes   True  

[98 rows x 15 columns]

##### Q2.Get the records of passengers who survived.

In [56]:
table[table['survived']==1]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
8           1       3  female  27.0      0      2  11.1333        S   Third   
9           1       2  female  14.0      1      0  30.0708        C  Second   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
875         1       3  female  15.0      0      0   7.2250        C   Third   
879         1       1  female  56.0      0      1  83.1583        C   First   
880         1       2  female  25.0      0      1  26.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
889         1       1    male  26.0      0      0  30.0000        C   First   

       who  adult_male deck  embark_town alive  alone  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
8    woman       False  NaN  Southampton   yes  False  
9    child       False  NaN    Cherbourg   yes  False  
..     ...         ...  ...          ...   ...    ...  
875  child       False  NaN    Cherbourg   yes   True  
879  woman       False    C    Cherbourg   yes  False  
880  woman       False  NaN  Southampton   yes  False  
887  woman       False    B  Southampton   yes   True  
889    man        True    C    Cherbourg   yes   True  

[342 rows x 15 columns]

##### Q3. Get the records of passengers who did not survive and were male.

In [58]:
table[(table['sex']=='male') & (table['survived']==0)]

survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third   
4           0       3  male  35.0      0      0   8.0500        S   Third   
5           0       3  male   NaN      0      0   8.4583        Q   Third   
6           0       1  male  54.0      0      0  51.8625        S   First   
7           0       3  male   2.0      3      1  21.0750        S   Third   
..        ...     ...   ...   ...    ...    ...      ...      ...     ...   
881         0       3  male  33.0      0      0   7.8958        S   Third   
883         0       2  male  28.0      0      0  10.5000        S  Second   
884         0       3  male  25.0      0      0   7.0500        S   Third   
886         0       2  male  27.0      0      0  13.0000        S  Second   
890         0       3  male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
6      man        True    E  Southampton    no   True  
7    child       False  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
881    man        True  NaN  Southampton    no   True  
883    man        True  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
886    man        True  NaN  Southampton    no   True  
890    man        True  NaN   Queenstown    no   True  

[468 rows x 15 columns]

##### Q4. Get the records of passengers who were in the first class and had a fare greater than 100.

In [64]:
table[(table['class']=='First') & (table['fare']>100)]

survived  pclass     sex    age  sibsp  parch      fare embarked  class  \
27          0       1    male  19.00      3      2  263.0000        S  First   
31          1       1  female    NaN      1      0  146.5208        C  First   
88          1       1  female  23.00      3      2  263.0000        S  First   
118         0       1    male  24.00      0      1  247.5208        C  First   
195         1       1  female  58.00      0      0  146.5208        C  First   
215         1       1  female  31.00      1      0  113.2750        C  First   
258         1       1  female  35.00      0      0  512.3292        C  First   
268         1       1  female  58.00      0      1  153.4625        S  First   
269         1       1  female  35.00      0      0  135.6333        S  First   
297         0       1  female   2.00      1      2  151.5500        S  First   
299         1       1  female  50.00      0      1  247.5208        C  First   
305         1       1    male   0.92      1      2  151.5500        S  First   
306         1       1  female    NaN      0      0  110.8833        C  First   
307         1       1  female  17.00      1      0  108.9000        C  First   
311         1       1  female  18.00      2      2  262.3750        C  First   
318         1       1  female  31.00      0      2  164.8667        S  First   
319         1       1  female  40.00      1      1  134.5000        C  First   
325         1       1  female  36.00      0      0  135.6333        C  First   
332         0       1    male  38.00      0      1  153.4625        S  First   
334         1       1  female    NaN      1      0  133.6500        S  First   
337         1       1  female  41.00      0      0  134.5000        C  First   
341         1       1  female  24.00      3      2  263.0000        S  First   
373         0       1    male  22.00      0      0  135.6333        C  First   
377         0       1    male  27.00      0      2  211.5000        C  First   
380         1       1  female  42.00      0      0  227.5250        C  First   
390         1       1    male  36.00      1      2  120.0000        S  First   
393         1       1  female  23.00      1      0  113.2750        C  First   
435         1       1  female  14.00      1      2  120.0000        S  First   
438         0       1    male  64.00      1      4  263.0000        S  First   
498         0       1  female  25.00      1      2  151.5500        S  First   
505         0       1    male  18.00      1      0  108.9000        C  First   
527         0       1    male    NaN      0      0  221.7792        S  First   
537         1       1  female  30.00      0      0  106.4250        C  First   
544         0       1    male  50.00      1      0  106.4250        C  First   
550         1       1    male  17.00      0      2  110.8833        C  First   
557         0       1    male    NaN      0      0  227.5250        C  First   
581         1       1  female  39.00      1      1  110.8833        C  First   
609         1       1  female  40.00      0      0  153.4625        S  First   
659         0       1    male  58.00      0      2  113.2750        C  First   
660         1       1    male  50.00      2      0  133.6500        S  First   
679         1       1    male  36.00      0      1  512.3292        C  First   
689         1       1  female  15.00      0      1  211.3375        S  First   
698         0       1    male  49.00      1      1  110.8833        C  First   
700         1       1  female  18.00      1      0  227.5250        C  First   
708         1       1  female  22.00      0      0  151.5500        S  First   
716         1       1  female  38.00      0      0  227.5250        C  First   
730         1       1  female  29.00      0      0  211.3375        S  First   
737         1       1    male  35.00      0      0  512.3292        C  First   
742         1       1  female  21.00      2      2  262.3750        C  First   
763  

##### Q5. Get the average age of passengers who survived compared to those who did not survive.

In [68]:
average_age=table.groupby('survived')['age'].mean()
print(average_age)

survived
0    30.626179
1    28.343690
Name: age, dtype: float64


##### Q6. Get the records of passengers who embarked from 'C' (Cherbourg) and are female.

In [70]:
table.head(3)
table[(table['embarked']=='C') & (table['sex']=='female')]

survived  pclass     sex   age  sibsp  parch      fare embarked   class  \
1           1       1  female  38.0      1      0   71.2833        C   First   
9           1       2  female  14.0      1      0   30.0708        C  Second   
19          1       3  female   NaN      0      0    7.2250        C   Third   
31          1       1  female   NaN      1      0  146.5208        C   First   
39          1       3  female  14.0      1      0   11.2417        C   Third   
..        ...     ...     ...   ...    ...    ...       ...      ...     ...   
858         1       3  female  24.0      0      3   19.2583        C   Third   
866         1       2  female  27.0      1      0   13.8583        C  Second   
874         1       2  female  28.0      1      0   24.0000        C  Second   
875         1       3  female  15.0      0      0    7.2250        C   Third   
879         1       1  female  56.0      0      1   83.1583        C   First   

       who  adult_male deck embark_town alive  alone  
1    woman       False    C   Cherbourg   yes  False  
9    child       False  NaN   Cherbourg   yes  False  
19   woman       False  NaN   Cherbourg   yes   True  
31   woman       False    B   Cherbourg   yes  False  
39   child       False  NaN   Cherbourg   yes  False  
..     ...         ...  ...         ...   ...    ...  
858  woman       False  NaN   Cherbourg   yes  False  
866  woman       False  NaN   Cherbourg   yes  False  
874  woman       False  NaN   Cherbourg   yes  False  
875  child       False  NaN   Cherbourg   yes   True  
879  woman       False    C   Cherbourg   yes  False  

[73 rows x 15 columns]

##### Q7. Get the records of passengers who have missing age values.

In [7]:
table.head(25)
table[table['age'].isnull()]

survived  pclass     sex  age  sibsp  parch     fare embarked   class  \
5           0       3    male  NaN      0      0   8.4583        Q   Third   
17          1       2    male  NaN      0      0  13.0000        S  Second   
19          1       3  female  NaN      0      0   7.2250        C   Third   
26          0       3    male  NaN      0      0   7.2250        C   Third   
28          1       3  female  NaN      0      0   7.8792        Q   Third   
..        ...     ...     ...  ...    ...    ...      ...      ...     ...   
859         0       3    male  NaN      0      0   7.2292        C   Third   
863         0       3  female  NaN      8      2  69.5500        S   Third   
868         0       3    male  NaN      0      0   9.5000        S   Third   
878         0       3    male  NaN      0      0   7.8958        S   Third   
888         0       3  female  NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  
5      man        True  NaN   Queenstown    no   True  
17     man        True  NaN  Southampton   yes   True  
19   woman       False  NaN    Cherbourg   yes   True  
26     man        True  NaN    Cherbourg    no   True  
28   woman       False  NaN   Queenstown   yes   True  
..     ...         ...  ...          ...   ...    ...  
859    man        True  NaN    Cherbourg    no   True  
863  woman       False  NaN  Southampton    no  False  
868    man        True  NaN  Southampton    no   True  
878    man        True  NaN  Southampton    no   True  
888  woman       False  NaN  Southampton    no  False  

[177 rows x 15 columns]

##### Q8. Get the number of siblings/spouses aboard for passengers who did not survive.

In [10]:
table.head(25)
table[(table['sibsp']==1) & (table['survived']==0)]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
13          0       3    male  39.0      1      5  31.2750        S   Third   
18          0       3  female  31.0      1      0  18.0000        S   Third   
34          0       1    male  28.0      1      0  82.1708        C   First   
35          0       1    male  42.0      1      0  52.0000        S   First   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
817         0       2    male  31.0      1      1  37.0042        C  Second   
852         0       3  female   9.0      1      1  15.2458        C   Third   
854         0       2  female  44.0      1      0  26.0000        S  Second   
861         0       2    male  21.0      1      0  11.5000        S  Second   
888         0       3  female   NaN      1      2  23.4500        S   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
13     man        True  NaN  Southampton    no  False  
18   woman       False  NaN  Southampton    no  False  
34     man        True  NaN    Cherbourg    no  False  
35     man        True  NaN  Southampton    no  False  
..     ...         ...  ...          ...   ...    ...  
817    man        True  NaN    Cherbourg    no  False  
852  child       False  NaN    Cherbourg    no  False  
854  woman       False  NaN  Southampton    no  False  
861    man        True  NaN  Southampton    no  False  
888  woman       False  NaN  Southampton    no  False  

[97 rows x 15 columns]

## String operations

##### Q1. How to replace something inside a string 

In [3]:
n='My name is Vijayarajan'
n.replace('My name is','I am')  ### Replace will not change the original text, it will temp replace and display

'I am Vijayarajan'

##### Q2. How to change the original string   

###### To change the original text in Python, use the replace method to create a new string and assign it back to the same variable.

In [14]:
n.upper()

'MY NAME IS VIJAYARAJAN'

In [15]:
n.lower()

'my name is vijayarajan'

In [16]:
n.title()

'My Name Is Vijayarajan'

##### Q3. What is swapcase

###### The swapcase method in Python is used to convert all uppercase letters in a string to lowercase and all lowercase letters to uppercase. Essentially, it swaps the case of each letter in the string.

In [17]:
n.swapcase()

'mY NAME IS vIJAYARAJAN'

##### Q4 What is capitalize 

###### The capitalize method in Python converts the first character of a string to uppercase and all other characters to lowercase.

In [37]:
n.capitalize()

'My name is vijayarajan'

##### Q5 What is Casefold

In [19]:
text = "Straße"  # German word for "street"

lower_text = text.lower()
casefold_text = text.casefold()

print(lower_text)   # Output: straße
print(casefold_text)  # Output: strasse

straße
strasse


###### In this example, lower converts "Straße" to "straße", but casefold converts it to "strasse", handling the special character "ß" more effectively for comparisons.

In [28]:
print(n.find('y'))
print(n.find('i',9,15))

1
12


##### Q6 What is enumerate

In [31]:
enumerated_list = list(enumerate(n))
print(enumerated_list)

[(0, 'M'), (1, 'y'), (2, ' '), (3, 'n'), (4, 'a'), (5, 'm'), (6, 'e'), (7, ' '), (8, 'i'), (9, 's'), (10, ' '), (11, 'V'), (12, 'i'), (13, 'j'), (14, 'a'), (15, 'y'), (16, 'a'), (17, 'r'), (18, 'a'), (19, 'j'), (20, 'a'), (21, 'n')]


##### Q7 how to find a index in a string

In [2]:
text = "Hello, world!"
index = text.index("o")
print(index)  # Output: 4

4


## String Slicing

In [38]:
n[11:16]

'Vijay'

In [47]:
n[::2]    ## It will skip the 2nd value 

'M aei iaaaa'

In [15]:
print(n)
n[0:21:5]    ## In this it will take every fifth element 

My name is Vijayarajan


'Mm ya'

##### What does the split will do
###### The split method in Python divides a string into a list of substrings based on a specified delimiter

In [21]:
n.split()     

['My', 'name', 'is', 'Vijayarajan']

In [23]:
d='*Hi*I*am*Vijay*'
d.split('*')

['', 'Hi', 'I', 'am', 'Vijay', '']

##### What does strip will do
###### removes the space/any symbol at beginning and at the end

In [24]:
d.strip('*')

'Hi*I*am*Vijay'

## String Formating 

###### Formating with % operator 

In [36]:
name='VIJAYARAJAN'
age=21
location='Chennai'

string='Hi!, My name is %s' %name
print(string)

ans='Hi! My name is %s. I am %s yrs old and I am from %s' %(name,age,location)
print(ans)

inti="When 5 is multipled with 1000.55555 then the value is %3.2f " %(5002.77775)
print(inti)

Hi!, My name is VIJAYARAJAN
Hi! My name is VIJAYARAJAN. I am 21 yrs old and I am from Chennai
When 5 is multipled with 1000.55555 then the value is 5002.78 


###### Formating with format() method

In [38]:
t='he is learning {} today'.format('Python')
t

'he is learning Python today'

In [41]:
r='He is {1} and he is {0}'.format('clever','Smart')
r

'He is Smart and he is clever'

In [42]:
d='I have done my {a} in {b} from {c}'.format(a='UG',b='Physics',c='Loyola')
d

'I have done my UG in Physics from Loyola'

###### Formating strings using literals aka f'strings

In [44]:
course='DSE'
institute = 'Great learning'
location='chennai'
q1=f'I am doing {course} course from {institute} which is in {location}'
print(q1)

I am doing DSE course from Great learning which is in chennai


In [46]:
n1=int(input('Enter a number 1 : '))
n2=int(input('Enter a number 2 : '))
output=f'When {n1} is multipled with {n2} then the result is {n1*n2}'
print(output)

Enter a number 1 :  5
Enter a number 2 :  5


When 5 is multipled with 5 then the result is 25


### Datatypes 

###### String
###### float
###### int
###### list    ------Mutable,ordered
###### tuple   ------Immutable,Ordered
###### dict    ------Mutable,Unordered
###### set    -------Mutable,Unordered 
###### bool 

## 1. List

In [51]:
lists=n.split()
lists

['My', 'name', 'is', 'Vijayarajan']

##### How can I combine two list

In [53]:
numbers=[1,2,3]*2
combined_list=numbers+lists
print(combined_list)

[1, 2, 3, 1, 2, 3, 'My', 'name', 'is', 'Vijayarajan']


##### How to count the no of elements in list

In [55]:
print(len(lists))

4


##### How to access a specific eleement

In [58]:
print(lists[0:2])

['My', 'name']


##### How to change a element in the list

In [60]:
lists[0]='I'
lists[1]='am'
lists[2]='T S'
print(lists)         # Note: It will do a permanent change

['I', 'am', 'T S', 'Vijayarajan']


##### How to remove a specific element 

In [62]:
lists.remove('T S')
print(lists)

['I', 'am', 'Vijayarajan']


##### How to get a range of values in a list

In [63]:
range=list(range(10))
print(range)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


##### How to split a list into more lists

In [64]:
lists

['I', 'am', 'Vijayarajan']

In [65]:
first=lists[0]
first,*others=lists
print(first)
print(others)

I
['am', 'Vijayarajan']


##### How to add using index 

In [72]:
lists.append('T S')
print(lists)   ## Adds a single element to the end of the list.

['I', 'am', 'Vijayarajan', 'T S']


In [74]:
lists.insert(0,'HI!')
print(lists)    ## Adds to the specific position in the list

['HI!', 'I', 'am', 'Vijayarajan', 'T S']


In [75]:
lists.extend(['Iam','from','Chennai'])
print(lists)    ## Adds all elements of an iterable (e.g., another list) to the end of the list.

['HI!', 'I', 'am', 'Vijayarajan', 'T S', 'Iam', 'from', 'Chennai']


##### How to remove using index

In [77]:
lists.pop(-3)
print(lists)    ##Removes and returns the element at a specified index (or the last element if no index is provided).

['HI!', 'I', 'am', 'Vijayarajan', 'T S', 'from', 'Chennai']


##### What is the difference betweeen Sort() and Sorted()

##### sort() when you want to change the original list directly, and use sorted() when you want a new sorted list and keep the original list the same

In [1]:
cards = [3, 1, 4, 1, 5]
cards.sort()
print(cards)  # Now the cards are [1, 1, 3, 4, 5]

[1, 1, 3, 4, 5]


In [2]:
cards = [3, 1, 4, 1, 5]
sorted_cards = sorted(cards)
print(cards)  # The original cards are still [3, 1, 4, 1, 5]
print(sorted_cards)  # The new sorted cards are [1, 1, 3, 4, 5]

[3, 1, 4, 1, 5]
[1, 1, 3, 4, 5]


##### How to sort strings

In [5]:
x=['X','S','T','A']
x.sort()
print(x)

['A', 'S', 'T', 'X']


##### How to sort using number of letters

In [15]:
l = ['apple', 'cake', 'orange', 'kiwi']
l.sort(key=len)  # Sorts the list by the length of the strings
print(l)  # Output will be ['cake', 'kiwi', 'apple', 'orange']

['cake', 'kiwi', 'apple', 'orange']


##### How to reverse a list

In [16]:
names = ['apple', 'cake', 'orange', 'kiwi']
names.reverse()  # Reverses the order of the elements in the list
print(names)  # Output will be ['kiwi', 'orange', 'cake', 'apple']

['kiwi', 'orange', 'cake', 'apple']


## 2. Tuple
##### An ordered, immutable collection of elements, which can be of different types, used to store a sequence of data.

##### 2a) how to Access a Items in tuple

In [17]:
my_tuple = (1, 2, 3, 'apple', 'banana')
print(my_tuple[0])  # Output: 1
print(my_tuple[3])  # Output: apple

1
apple


##### How to find a length of a tuple 

In [18]:
print(len(my_tuple))  # Output: 5

5


##### how to Concatenate  a tuple

In [19]:
tuple1 = (1, 2, 3)
tuple2 = ('apple', 'banana')
combined = tuple1 + tuple2
print(combined)  # Output: (1, 2, 3, 'apple', 'banana')

(1, 2, 3, 'apple', 'banana')


##### How to unpack a tuple

In [20]:
my_tuple = (1, 'apple', 3.5)
a, b, c = my_tuple
print(a)  # Output: 1
print(b)  # Output: apple
print(c)  # Output: 3.5

1
apple
3.5


## 3. Dictionary 
##### A dictionary in Python is a collection of key-value pairs, where each key is unique and is used to retrieve its corresponding value

In [29]:
favorite_colors = {
    "Alice": "blue",
    "Bob": "green",
    "Charlie": "red"
}

#### How to add new key and value in dictionary

In [30]:
favorite_colors["Diana"] = "yellow"
favorite_colors

{'Alice': 'blue', 'Bob': 'green', 'Charlie': 'red', 'Diana': 'yellow'}

#### How to get the value for a key:

In [31]:
print(favorite_colors["Alice"])  # Output: blue

blue


#### How to get keys and values of a dict

In [5]:
mix_dictionary = {0:3, 'x':5, 1:2}
keys = mix_dictionary.keys()
keys1 = mix_dictionary.values()
print(keys)
print(keys1)

dict_keys([0, 'x', 1])
dict_values([3, 5, 2])


## 4. Nested Dictionay
##### A nested dictionary is a dictionary that contains other dictionaries as its values.

In [32]:
batch={'boys':{'Gokul':25,'Surya':23},'girls':{'Devika':29,'Priya':23}}
print(batch['girls']['Priya'])

23


##### How to use zip

In [33]:
names= ["Alice", "Bob", "Charlie"]
ages=[10, 12, 11]
combined = list(zip(names, ages))
print(combined)  # Output: [('Alice', 10), ('Bob', 12), ('Charlie', 11)]

[('Alice', 10), ('Bob', 12), ('Charlie', 11)]


##### How to use fromkeys

##### he fromkeys method creates a new dictionary with specified keys and sets a default value for all the keys. It’s like filling a dictionary with keys and giving each key the same starting value.

In [34]:
names = ["Alice", "Bob", "Charlie"]
default_value = 0

dictionary = dict.fromkeys(names, default_value)
print(dictionary)  # Output: {'Alice': 0, 'Bob': 0, 'Charlie': 0}

{'Alice': 0, 'Bob': 0, 'Charlie': 0}


## 5. Sets
##### A set is a collection of unique items in Python. It means you can store multiple items in a set, but each item can only appear once, and the order of the items doesn't matter.

In [35]:
# Creating a set
colors = {"red", "blue", "green"}

# Trying to add a duplicate item
colors.add("blue")  # This won't add another "blue" marble
print(colors)  # Output: {'red', 'blue', 'green'}

{'red', 'green', 'blue'}


#### How to add a item to a set

In [36]:
colors.add("yellow")
print(colors)  # Output: {'red', 'blue', 'green', 'yellow'}

{'red', 'green', 'blue', 'yellow'}


#### How to remove a item

In [37]:
colors.remove("blue")
print(colors)  # Output: {'red', 'green', 'yellow'}

{'red', 'green', 'yellow'}


#### How to Check if an item is in the set:

In [38]:
print("green" in colors)  # Output: True
print("blue" in colors)   # Output: False

True
False


#### How to convert string into set and split each word

In [3]:
sentence_1 = 'We shall analyse the data using python' 
d=set(sentence_1.split())
d

{'We', 'analyse', 'data', 'python', 'shall', 'the', 'using'}

#### How to Find the number of items:

In [39]:
print(len(colors))  # Output: 3 (or the number of unique items)

3


#### How to combine sets(Union)

In [40]:
more_colors = {"purple", "orange"}
all_colors = colors | more_colors
print(all_colors)  # Output: {'red', 'green', 'yellow', 'purple', 'orange'}

{'red', 'orange', 'yellow', 'green', 'purple'}


#### How to Find common items (Intersection):

In [2]:
colors1 = {"red", "blue", "green"}
colors2 = {"blue", "green", "yellow"}
common_colors = colors1 & colors2
print(common_colors)  # Output: {'blue', 'green'}

{'green', 'blue'}


In [3]:
colors1.intersection(colors2)

{'blue', 'green'}

#### How to Find items in one set but not in the other (Difference):

In [42]:
unique_colors = colors1 - colors2
print(unique_colors)  # Output: {'red'}

{'red'}


In [43]:
s1 = {1, 2, 3, 4}
s2 = {3, 4, 5, 6}
s3 = {100, 200}

#### Symmetric_difference
##### The symmetric_difference method returns a new set with elements that are in either of the sets but not in both.

In [44]:
s1 = {1, 2, 3, 4}
s2 = {3, 4, 5, 6}
s3 = {100, 200}
result = s1.symmetric_difference(s2)
print(result)  # Output: {1, 2, 5, 6}

{1, 2, 5, 6}


#### isdisjoint
##### The isdisjoint method checks if two sets have no elements in common. It returns True if they are disjoint (no overlap) and False otherwise.

In [45]:
result = s1.isdisjoint(s3)
print(result)  # Output: True

True


## Conditional Statements in Python
##### Conditional statements are used to make decisions in your code. They allow you to execute different blocks of code based on certain conditions.

In [46]:
number = 5

if number > 0:
    print("The number is positive.")
elif number < 0:
    print("The number is negative.")
else:
    print("The number is zero.")

The number is positive.


## While Loop
#### The while loop in Python repeatedly executes a block of code as long as a specified condition is True. Once the condition becomes False, the loop stops.

In [48]:
count = 0

while count < 5:
    print(count)
    count += 1


0
1
2
3
4


### Continue in while loop
#### The continue statement skips the rest of the code inside the current iteration of the loop and moves on to the next iteration.

In [49]:
count = 0

while count < 5:
    count += 1
    if count % 2 == 0:
        continue  # Skip the rest of the loop for even numbers
    print(count)

1
3
5


### Break in While loop
#### The break statement exits the loop immediately, regardless of whether the loop's condition is True or not.

In [50]:
count = 0

while count < 5:
    if count == 3:
        break  # Exit the loop when count is 3
    print(count)
    count += 1

0
1
2


### Pass in while loop
####  The pass statement is a placeholder that does nothing. It is used when a statement is required syntactically but you don’t want to execute any code.

In [52]:
count = 0

while count < 5:
    if count % 2 == 0:
        pass  # Do nothing for even numbers
    else:
        print(count)
    count += 1

1
3


### FOR loops
#### The for loop in Python is used to iterate over a sequence (like a list, tuple, string, or range) and execute a block of code for each item in that sequence.

In [53]:
fruits = ["apple", "banana", "cherry"]

for fruit in fruits:
    print(fruit)


apple
banana
cherry


In [54]:
for letter in "hello":
    print(letter)


h
e
l
l
o


In [55]:
for i in range(5):
    print(i)

0
1
2
3
4


In [56]:
numbers = (10, 20, 30)

for number in numbers:
    print(number)

10
20
30


In [57]:
fruits = ["apple", "banana", "cherry"]

for index, fruit in enumerate(fruits):
    print(index, fruit)

0 apple
1 banana
2 cherry


### List Comprehension

List comprehension is a concise way to create lists in Python by performing operations on existing lists. It offers a more readable and efficient alternative to traditional for loops when constructing lists.

### new_list = [expression for item in iterable if condition]

In [11]:
numbers = [1, 2, 3, 4, 5]

# Square each number and create a new list
squares = [x**2 for x in numbers]
print(squares)  # Output: [1, 4, 9, 16, 25]

# Create a list of even numbers
even_numbers = [x for x in numbers if x % 2 == 0]
print(even_numbers)  # Output: [2, 4]

[1, 4, 9, 16, 25]
[2, 4]


### Python Functions

A function is a block of code that performs a specific task. It's like a mini-program within your larger program. Functions help to organize your code, make it reusable, and improve readability.

#### Types of Functions

1. Built-in Functions
2. User-defined Functions
3. Lambda Functions
4. Recursive Functions (A recursive function is a function that calls itself directly or indirectly.)

#### What are funtion arguments in python

Function arguments are values passed to a function when it's called. They provide input to the function, allowing it to perform calculations or operations based on those values.

##### Positional arguments
##### Keyword arguments
##### Default arguments
##### Arbitrary positional arguments (*args)
##### Arbitrary keyword arguments (**kwargs)

#### 1. Positional Arguments
These are the most common type of arguments.
Their order matters.
They are assigned to parameters in the function definition based on their position.
Python

In [1]:
def greet(name, age):
  print("Hello,", name, "You are", age, "years old.")

greet("Alice", 30)  # Output: Hello, Alice You are 30 years old.

Hello, Alice You are 30 years old.


#### 2. Keyword Arguments
These arguments specify the parameter name explicitly.
Order doesn't matter.
They provide more flexibility and readability.
Python

In [2]:
def greet(name, age):
  print("Hello,", name, "You are", age, "years old.")

greet(age=30, name="Alice")  # Output: Hello, Alice You are 30 years old.

Hello, Alice You are 30 years old.


#### 3. Default Arguments
These arguments have default values.
If no value is provided during the function call, the default value is used.
Python

In [3]:
def greet(name, age=30):
  print("Hello,", name, "You are", age, "years old.")

greet("Bob")  # Output: Hello, Bob You are 30 years old.
greet("Charlie", 25)  # Output: Hello, Charlie You are 25 years old.

Hello, Bob You are 30 years old.
Hello, Charlie You are 25 years old.


#### 4. Arbitrary Arguments (*args)
This allows you to pass a variable number of positional arguments to a function.
The arguments are packed into a tuple.
Python

In [5]:
def sum_numbers(*args):
  total = 0
  for num in args:
    total += num
  return total
result = sum_numbers(1, 2, 3, 4)  # Output: 10
result

10

#### 5. Arbitrary Keyword Arguments (**kwargs)
This allows you to pass a variable number of keyword arguments to a function.
The arguments are packed into a dictionary.
Python

In [7]:
def print_info(**kwargs):
  for key, value in kwargs.items():
    print(key, ":", value)

print_info(name="Alice", age=30, city="New York")

name : Alice
age : 30
city : New York


### Global Variable vs Local Variable:

Global Variable:

Declared outside any function.
Accessible from anywhere in the program.

Local Variable:

Declared within a function.
Only accessible within that function.

In [8]:
x = 10  # Global variable

def my_function():
  print(x)  # Accessing global variable

my_function()

10


In [9]:
def my_function():
  y = 20  # Local variable
  print(y)

my_function()

20


## What is lambda funtions

Lambda Functions
A lambda function is a small, anonymous function defined in a single line using the lambda keyword.

In [11]:
double = lambda x: x * 2
result = double(5)
print(result)  # Output: 10

10


Lambda functions can take any number of arguments but only have one expression.   
They are often used with higher-order functions like map, filter, and reduce.

### Lambda using map 

The map function applies a given function to each item of an iterable (like a list, tuple, or string) and returns an iterator.

In [12]:
numbers = [1, 2, 3, 4, 5]
squared = map(lambda x: x * x, numbers)
print(list(squared))  # Output: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


### Lambda using Filter

The filter function creates an iterator from the elements of an iterable for which a function returns True.

In [13]:
numbers = [1, 2, 3, 4, 5]
even_numbers = filter(lambda x: x % 2 == 0, numbers)
print(list(even_numbers))  # Output: [2, 4]

[2, 4]


### Lambda using reduce 

The reduce function applies a function of two arguments cumulatively to the items of an iterable, from left to right, so as to reduce the iterable to a single value.

In [47]:
from functools import reduce

numbers = [1, 2, 3, 4]
product = reduce(lambda x, y: x * y, numbers)
print(product)  # Output: 24

24


# What are Numpy 

NumPy is a powerful Python library used for working with numerical data.

NumPy Arrays: These are the core data structure in NumPy. They are like lists but much faster and better for mathematical operations.   

Example: [1, 2, 3] is a Python list, while np.array([1, 2, 3]) is a NumPy array.

### HOW TO INSTALL NUMPY

In [2]:
import numpy as np

#### Whats the diffrence between Numpyarray and list

##### Lists are flexible containers for various data types, while arrays are efficient for storing homogeneous data with fixed size.

In [5]:
# List example
shopping_list = ["apples", 3, "milk", True]
print(shopping_list)

# Array example (using NumPy)
import numpy as np
student_heights = np.array([165, 172, 158, 170])
print(student_heights)

['apples', 3, 'milk', True]
[165 172 158 170]


### Whats The difference between Array and Numpy array

Arrays: If you need a simple data structure to store a collection of elements and don't require high performance numerical computations.


NumPy arrays: If you're working with numerical data and need to perform complex mathematical operations efficiently.

In [6]:
import array
import numpy as np

# Array
my_array = array.array('i', [1, 2, 3])  # 'i' for signed integers
print(my_array)
# NumPy array
my_numpy_array = np.array([1, 2, 3])
print(my_numpy_array)

array('i', [1, 2, 3])
[1 2 3]


### Single-Dimensional Array

Imagine a list of items. That's essentially a one-dimensional array. It's a linear collection of elements, each identified by a unique index.

In [7]:
# A single-dimensional array of numbers
numbers = np.array([1, 2, 3, 4, 5])
numbers

array([1, 2, 3, 4, 5])

### Two-Dimensional Array

A two-dimensional array is like a table with rows and columns. It's a collection of one-dimensional arrays.

In [8]:
# A two-dimensional array (matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Three-Dimensional Array

Think of a cube. A three-dimensional array is a collection of two-dimensional arrays stacked on top of each other. It has depth, in addition to rows and columns.   

In [9]:
# A three-dimensional array
cube = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]],
                 [[9, 10], [11, 12]]])
cube 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

### How to get dimensions of each 
##### .ndim

In [13]:
One_d=numbers.ndim
Two_d=matrix.ndim
Three_d=cube.ndim
print(f'The dimension of numbers is {One_d}')
print(f'The dimension of matrix is {Two_d}')
print(f'The dimension of cude is {Three_d}')

The dimension of numbers is 1
The dimension of matrix is 2
The dimension of cude is 3


### How to get shape

In [15]:
one_shape=numbers.shape
two_shape=matrix.shape
three_shape=cube.shape
print(f'The shape of numbers is {one_shape}')
print(f'The shape of matrix is {two_shape}')
print(f'The shape of cude is {three_shape}')

The shape of numbers is (5,)
The shape of matrix is (3, 3)
The shape of cude is (3, 2, 2)


### We can also tell in which dtype we want to store a array like int32 or int16

In [26]:
# Creating a 2D array (list of lists)
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]) 
print(array_2d.dtype)
array_2d.itemsize ### This is in int32 bit coz it has 4 bype 

int32


4

In [27]:
array_2d_new = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.int16)#### Using this we can specify the dtype
print(array_2d_new.dtype)
array_2d_new.itemsize       

int16


2

### How to access specific elements,rows,columns in an 2D array

In [45]:
acc_array=np.array([[1,2,3],[4,5,6]])
print(acc_array)
print(' ')
# If i want to access the number 3 in this
print(acc_array[0,2])    #acc_array[row,column]

# If i want to access the 1st row
print(acc_array[0])

#If i want to access a column
print(acc_array[:,1])

#If i want to access the 1st row elements 1 and 3 using step
print(acc_array[0,0::2])   # start:stop:step

[[1 2 3]
 [4 5 6]]
 
3
[1 2 3]
[2 5]
[1 3]


In [58]:
## If i want to access specific elements in 3D array 
acc_array_3d = np.array([
    [[2, 17], [45, 78]],
    [[88, 92], [60, 76]],
    [[76, 33], [20, 18]]
])
acc_array_3d[0,0,1]

17

### How to change the elements

In [47]:
acc_array[1,2]=7
acc_array

array([[1, 2, 3],
       [4, 5, 7]])

In [6]:
acc_array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
acc_array_2d[:,1]=[22,55,88] 
acc_array_2d

array([[ 1, 22,  3],
       [ 4, 55,  6],
       [ 7, 88,  9]])

In [62]:
acc_array_3d

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [68]:
# If i wwant change that 
acc_array_3d[:,0,1][0]=15
acc_array_3d

array([[[ 2, 15],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [72]:
acc_array_3d[:,0]=[[15,2],[92,88],[33,76]]
acc_array_3d

array([[[15,  2],
        [45, 78]],

       [[92, 88],
        [60, 76]],

       [[33, 76],
        [20, 18]]])

### Initiliazing different types of array

In [74]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.zeros((5,2,3),dtype='int32')

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [88]:
np.ones((3,3),dtype='str')

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

### How to form array with a given value

In [100]:
np.full((2,2,3),int(input('Enter a number : ')),dtype='float')

Enter a number :  88


array([[[88., 88., 88.],
        [88., 88., 88.]],

       [[88., 88., 88.],
        [88., 88., 88.]]])

### How to generate random integer array 

In [146]:
np.random.randint(100,size=(2,3,3))

array([[[80, 51, 52],
        [40, 34, 87],
        [51, 71, 31]],

       [[81, 48, 17],
        [71, 16, 62],
        [98, 28, 64]]])

### How to create a identity matrix

In [130]:
np.identity((3),dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### How to repeat an array

In [135]:
arr=np.array([1,2,3])
arr.repeat(3)   ##This will repeat each element in an array 

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [156]:
arr1=np.array([[1,2,3]])
rep=np.repeat(arr1,3,axis=0)
rep          ## This can be done only in 2D array and axis 0 represents rows and axis 1 represents column

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### How to reshape an array

In [9]:
reshape_arr=np.array([
    [10, 20, 30],
    [40, 50, 60],
])
d=reshape_arr.reshape(3,2)
d               ### In this, If there is 6 elements in the array you can reshape in the factors of that (like 1,2,3,6[2x3][3x2][6x1])

array([[10, 20],
       [30, 40],
       [50, 60]])

## Arithmetic operations in array

### 1.Addtion

In [167]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Add the arrays element-wise
result = array1 + array2

print(result)  # Output: [5 7 9]

[5 7 9]


#### 2.Subtraction 

In [168]:
# Create two arrays
array1 = np.array([5, 3, 7])
array2 = np.array([2, 1, 4])

# Subtract array2 from array1 element-wise
result = array1 - array2

print(result)  # Output: [3 2 3]

[3 2 3]


#### 3. Multiplication

In [171]:
# Create two arrays
array1 = np.array([2, 4, 1])
array2 = np.array([3, 2, 5])

# Multiply arrays element-wise
result = array1 * array2

print(result)  # Output: [ 6  8 5]

[6 8 5]


### 4.Division

In [174]:
# Create two arrays
array1 = np.array([10, 8, 6])
array2 = np.array([2, 4, 3])

# Divide array1 by array2 element-wise
result = array1 / array2

print(result)  # Output: [5.  2.  2.]

[5. 2. 2.]


## Arithmetic funtions in array

In [11]:
arithmetic_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

### 1.Addition

In [13]:
total_sum = np.sum(arithmetic_array)
total_sum

45

### 2.Minimun

In [179]:
min = np.min(arithmetic_array)
min

1

### 3.Maximun

In [180]:
max = np.max(arithmetic_array)
max

9

### 4.Mean

In [181]:
mean = np.mean(arithmetic_array)
mean

5.0

### 5. Square

In [182]:
squ = np.square(arithmetic_array)
squ

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### 6.Power

In [185]:
pow= np.power(arithmetic_array,3)
pow

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

## Concatenating Arrays in NumPy

### 1.Concatenating 1D Arrays

In [186]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = np.concatenate((array1, array2))
print(result)

[1 2 3 4 5 6]


### 2.Concatenating 2D Arrays

In [187]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along rows
result_rows = np.concatenate((array1, array2), axis=0)
print(result_rows)

# Concatenate along columns
result_cols = np.concatenate((array1, array2), axis=1)
print(result_cols)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Stacking an array

In [188]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = np.hstack((array1, array2))
print(result)

result1 = np.vstack((array1, array2))
print(result1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## Spliting an array

In [192]:
range_array=np.arange(9)
split=np.split(range_array,3)
split

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [200]:
split1=np.split(range_array,[1,3])
split1

[array([0]), array([1, 2]), array([3, 4, 5, 6, 7, 8])]

### Matrix Multiplication

In [14]:
import numpy as np

arr3=np.array([[2,3],[6,7],[8,9],[10,11]])
arr4=np.array([[10,11,12,13],[14,15,16,17]])
arr3.dot(arr4)

array([[ 62,  67,  72,  77],
       [158, 171, 184, 197],
       [206, 223, 240, 257],
       [254, 275, 296, 317]])

# Pandas

Pandas is a powerful Python library designed for data manipulation and analysis. It provides high-performance, easy-to-use data structures and data analysis tools. 

Handling heterogeneous data (different data types in a single object)
Powerful data indexing and selection.   
Time series analysis.
Data cleaning and preprocessing.   
Integration with NumPy for numerical computations.

Data Manipulation
Selection:
loc: Selects data based on labels.
iloc: Selects data based on integer positions.
at: Accesses a single value by label.
iat: Accesses a single value by integer position.


Modification:
assign: Assigns new columns to a DataFrame.
rename: Renames columns or indices.
drop: Drops specified rows or columns.
fillna: Fills missing values.
replace: Replaces values with other values.


Reshaping:
pivot_table: Creates a pivot table from the DataFrame.
melt: Unpivots a DataFrame from wide to long format.
stack: Stacks the column levels.
unstack: Unstacks the column levels.


Data Analysis

Descriptive Statistics:
describe: Generates descriptive statistics.
mean, median, mode, std, var, min, max: Calculate specific statistics.
count: Counts non-null values.
value_counts: Counts unique values.


Aggregation:
groupby: Groups data and applies functions.
agg: Applies aggregation functions to groups.
transform: Applies functions to groups and returns a DataFrame with the same shape.


Correlation and Covariance:
corr: Calculates correlation between columns.
cov: Calculates covariance between columns.

### How to Import Pandas

In [125]:
import pandas as pd
import numpy as np

### Difference between Series and Dataframe

single column of data is called Series. Series is a 1D array

A table with rows and columns are called Dataframe

### How to create a series

##### There are three ways of creating a series
##### 1. Using Scalar values
##### 2. Using Dictionary
##### 3. Using Numpy array

#### 1. Using Scalar values

In [63]:
a = ['Python','Java','C++','C','HTML']
i = ['1', '2', '3', '4', '5']
series = pd.Series(data=a, index=i)
print(series)

1    Python
2      Java
3       C++
4         C
5      HTML
dtype: object


In [67]:
b = ['Python','Java','C++','C','HTML']
series = pd.Series(data=b, index=np.arange(1,6))
print(series)

1    Python
2      Java
3       C++
4         C
5      HTML
dtype: object


#### 2. Using Dictionary

In [68]:
data = {'City': ['New York', 'Los Angeles', 'Chicago', 'Houston'],
        'Population': [8405837, 3971883, 2705994, 2325502]}

series = pd.Series(data)
print(series)

City          [New York, Los Angeles, Chicago, Houston]
Population         [8405837, 3971883, 2705994, 2325502]
dtype: object


#### 3. Using Numpy array

In [69]:
data = np.array(['apple', 'banana', 'orange', 'grape', 'kiwi'])
series = pd.Series(data)
print(series)

0     apple
1    banana
2    orange
3     grape
4      kiwi
dtype: object


### How to access a series

##### 1. Indexing
##### 2. Slicing

#### 1. Indexing
##### Positioning vs labeling

In [74]:
# Create a NumPy array
data = np.array(['apple', 'banana', 'orange', 'grape', 'kiwi'])

# Create a Pandas Series
series = pd.Series(data)

# Access elements using index position (0-based)
print(series[0])  # Output: apple
print(series[2])  # Output: orange

# Access elements using custom index labels
# (assuming you created a Series with a custom index)
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series['a'])

apple
orange
apple


#### 2. Slicing
##### Positioning vs Labeling

In [75]:
# Create a Series
data = [10, 20, 30, 40, 50]
s = pd.Series(data)

# Access elements by position
print(s[1:4])  # Elements at positions 1, 2, and 3

# Create a Series with custom index
data = [10, 20, 30, 40, 50]
index = ['a', 'b', 'c', 'd', 'e']
s = pd.Series(data, index=index)

# Access elements by label
print(s['b':'d'])  # Elements with labels 'b', 'c', and 'd'

1    20
2    30
3    40
dtype: int64
b    20
c    30
d    40
dtype: int64


### How to create a Dataframe using list

In [15]:
import pandas as pd

info = [['Alex', 25, 'New York'],
        ['Bob', 30, 'Los Angeles'],
        ['Charlie', 35, 'Chicago']]

df = pd.DataFrame(data=info, columns=['Name', 'Age', 'City'],index=[1,2,3])
print(df)

      Name  Age         City
1     Alex   25     New York
2      Bob   30  Los Angeles
3  Charlie   35      Chicago


### How to create a Dataframe using dictionary

In [20]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'location': ['New York', 'New York',None]
}
ind=[1,2,3]
df = pd.DataFrame(data,index=ind)

print(df)

      Name  age  location
1    Alice   25  New York
2      Bob   30  New York
3  Charlie   35      None


In [21]:
df.isnull()    ## used to detect missing values within a DataFrame or Series. 

Name    age  location
1  False  False     False
2  False  False     False
3  False  False      True

In [22]:
df.isnull().sum()   ## #calculates the total number of missing values in the entire DataFrame or Series 

Name        0
age         0
location    1
dtype: int64

In [23]:
df.index.to_list()  ## Accesses the index of the DataFrame, which is a Pandas Index object.   
                    ## to_list(): Converts the Pandas Index object into a Python list.

[1, 2, 3]

In [24]:
df.info()   ##  It gives you a quick overview of essential information about your data.

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      3 non-null      object
 1   age       3 non-null      int64 
 2   location  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes


In [25]:
df.nunique()  ##  calculates the number of unique values for each column in a Pandas DataFrame.

Name        3
age         3
location    1
dtype: int64

In [31]:
df['location'].nunique() ## calculate and return the number of unique values present in the 'location' column 

1

In [34]:
df.size   ## multiplying the number of rows by the number of columns.

9

In [36]:
df.tail(1)  ## Pandas returns the last row of a DataFrame

Name  age location
3  Charlie   35     None

### How to import file

In [3]:
df=pd.read_csv('pokemon.csv')
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

### How to read headers

In [38]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

### How to read each column

In [39]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [14]:
df[['Name','Total','Type 1']]

Name  Total   Type 1
0                Bulbasaur    318    Grass
1                  Ivysaur    405    Grass
2                 Venusaur    525    Grass
3    VenusaurMega Venusaur    625    Grass
4               Charmander    309     Fire
..                     ...    ...      ...
795                Diancie    600     Rock
796    DiancieMega Diancie    700     Rock
797    HoopaHoopa Confined    600  Psychic
798     HoopaHoopa Unbound    680  Psychic
799              Volcanion    600     Fire

[800 rows x 3 columns]

### How to read each row

### Loc[Rows,Colums]

In [84]:
df.loc[0]

#                     1
Name          Bulbasaur
Type 1            Grass
Type 2           Poison
Total               318
HP                   45
Attack               49
Defense              49
Sp. Atk              65
Sp. Def              65
Speed                45
Generation            1
Legendary         False
Name: 0, dtype: object

In [37]:
df.loc[0:6]

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   
5  5             Charmeleon   Fire     NaN    405  58      64       58   
6  6              Charizard   Fire  Flying    534  78      84       78   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False  
6      109       85    100           1      False

In [46]:
df.loc[0].to_list()

[1, 'Bulbasaur', 'Grass', 'Poison', 318, 45, 49, 49, 65, 65, 45, 1, False]

In [52]:
df.loc[:, ['Name', 'Total']].head(5)

Name  Total
0              Bulbasaur    318
1                Ivysaur    405
2               Venusaur    525
3  VenusaurMega Venusaur    625
4             Charmander    309

#### How to change a data using loc

In [75]:
df.loc[1,'Name']='ivysaur'
df.head(3)

#       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1  Bulbasaur  Grass  Poison    318  45      49       49       65       65   
1  2    ivysaur  Grass  Poison    405  60      62       63       80       80   
2  3   Venusaur  Grass  Poison    525  80      82       83      100      100   

   Speed  Generation  Legendary  
0     45           1      False  
1     60           1      False  
2     80           1      False

### What is the difference between iloc and loc

iloc
Integer-based indexing: Selects data based on their position in the DataFrame, starting from 0.   
Uses numerical indices to access rows and columns.   
Syntax: df.iloc[row_index, column_index]


loc
Label-based indexing: Selects data based on their row and column labels.   
Uses labels to access rows and columns.   
Syntax: df.loc[row_label, column_label]

### How to read a specific Location  
##### df.iloc(row,column)

In [16]:
df.iloc[2,1]

'Venusaur'

In [61]:
df.iloc[:,[1,4]].head(5)

Name  Total
0              Bulbasaur    318
1                Ivysaur    405
2               Venusaur    525
3  VenusaurMega Venusaur    625
4             Charmander    309

### How to sort values 

In [77]:
df.sort_values('Total',ascending=False) 

#                   Name   Type 1    Type 2  Total   HP  Attack  \
426  384  RayquazaMega Rayquaza   Dragon    Flying    780  105     180   
164  150    MewtwoMega Mewtwo Y  Psychic       NaN    780  106     150   
163  150    MewtwoMega Mewtwo X  Psychic  Fighting    780  106     190   
422  382    KyogrePrimal Kyogre    Water       NaN    770  100     150   
424  383  GroudonPrimal Groudon   Ground      Fire    770  100     180   
..   ...                    ...      ...       ...    ...  ...     ...   
13    10               Caterpie      Bug       NaN    195   45      30   
288  265                Wurmple      Bug       NaN    195   45      45   
446  401              Kricketot      Bug       NaN    194   37      25   
322  298                Azurill   Normal     Fairy    190   50      20   
206  191                Sunkern    Grass       NaN    180   30      30   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
426      100      180      100    115           3       True  
164       70      194      120    140           1       True  
163      100      154      100    130           1       True  
422       90      180      160     90           3       True  
424      160      150       90     90           3       True  
..       ...      ...      ...    ...         ...        ...  
13        35       20       20     45           1      False  
288       35       20       30     20           3      False  
446       41       25       41     25           4      False  
322       40       20       40     20           3      False  
206       30       30       30     30           2      False  

[800 rows x 13 columns]

In [80]:
df.sort_values(['Name','Total'])

#                     Name   Type 1  Type 2  Total   HP  Attack  \
510  460                Abomasnow    Grass     Ice    494   90      92   
511  460  AbomasnowMega Abomasnow    Grass     Ice    594   90     132   
68    63                     Abra  Psychic     NaN    310   25      20   
392  359                    Absol     Dark     NaN    465   65     130   
393  359          AbsolMega Absol     Dark     NaN    565   65     150   
..   ...                      ...      ...     ...    ...  ...     ...   
631  570                    Zorua     Dark     NaN    330   40      65   
46    41                    Zubat   Poison  Flying    245   40      45   
695  634                 Zweilous     Dark  Dragon    420   72      85   
794  718         Zygarde50% Forme   Dragon  Ground    600  108     100   
1      2                  ivysaur    Grass  Poison    405   60      62   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
510       75       92       85     60           4      False  
511      105      132      105     30           4      False  
68        15      105       55     90           1      False  
392       60       75       60     75           3      False  
393       60      115       60    115           3      False  
..       ...      ...      ...    ...         ...        ...  
631       40       80       40     65           5      False  
46        35       30       40     55           1      False  
695       70       65       70     58           5      False  
794      121       81       95     95           6       True  
1         63       80       80     60           1      False  

[800 rows x 13 columns]

### How to filter a data

In [82]:
df.loc[df['Total']>500]

#                       Name   Type 1  Type 2  Total  HP  Attack  \
2      3                   Venusaur    Grass  Poison    525  80      82   
3      3      VenusaurMega Venusaur    Grass  Poison    625  80     100   
6      6                  Charizard     Fire  Flying    534  78      84   
7      6  CharizardMega Charizard X     Fire  Dragon    634  78     130   
8      6  CharizardMega Charizard Y     Fire  Flying    634  78     104   
..   ...                        ...      ...     ...    ...  ..     ...   
795  719                    Diancie     Rock   Fairy    600  50     100   
796  719        DiancieMega Diancie     Rock   Fairy    700  50     160   
797  720        HoopaHoopa Confined  Psychic   Ghost    600  80     110   
798  720         HoopaHoopa Unbound  Psychic    Dark    680  80     160   
799  721                  Volcanion     Fire   Water    600  80     110   

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary  
2         83      100      100     80           1      False  
3        123      122      120     80           1      False  
6         78      109       85    100           1      False  
7        111      130       85    100           1      False  
8         78      159      115    100           1      False  
..       ...      ...      ...    ...         ...        ...  
795      150      100      150     50           6       True  
796      110      160      110    110           6       True  
797       60      150      130     70           6       True  
798       60      170      130     80           6       True  
799      120      130       90     70           6       True  

[224 rows x 13 columns]

In [87]:
df.loc[df['Total']>500,['Name','Total']].head(3)

Name  Total
2               Venusaur    525
3  VenusaurMega Venusaur    625
6              Charizard    534

In [94]:
df[df['Total']>500][['Name','Total']].head(3)

Name  Total
2               Venusaur    525
3  VenusaurMega Venusaur    625
6              Charizard    534

In [100]:
df[df['Type 1'].str.contains('Grass')].head(3)

#       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1  Bulbasaur  Grass  Poison    318  45      49       49       65       65   
1  2    ivysaur  Grass  Poison    405  60      62       63       80       80   
2  3   Venusaur  Grass  Poison    525  80      82       83      100      100   

   Speed  Generation  Legendary  
0     45           1      False  
1     60           1      False  
2     80           1      False

In [101]:
df[df['Type 1'].str.contains('rock',case=False)].head(3)

#      Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
80  74   Geodude   Rock  Ground    300  40      80      100       30       30   
81  75  Graveler   Rock  Ground    390  55      95      115       45       45   
82  76     Golem   Rock  Ground    495  80     120      130       55       65   

    Speed  Generation  Legendary  
80     20           1      False  
81     35           1      False  
82     45           1      False

In [105]:
df.query('Name=="Golem"')

#   Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
82  76  Golem   Rock  Ground    495  80     120      130       55       65   

    Speed  Generation  Legendary  
82     45           1      False

### How to describe a data

In [7]:
df.describe()

A        B     C
count  3.000000  2.00000   3.0
mean   2.333333  6.50000  10.0
std    1.527525  2.12132   1.0
min    1.000000  5.00000   9.0
25%    1.500000  5.75000   9.5
50%    2.000000  6.50000  10.0
75%    3.000000  7.25000  10.5
max    4.000000  8.00000  11.0

### How to add a column to a data

In [52]:
df['Attack-Defense']=df['Attack']-df['Defense']
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Attack-Defense  
0         65       65     45           1      False               0  
1         80       80     60           1      False              -1  
2        100      100     80           1      False              -1  
3        122      120     80           1      False             -23  
4         60       50     65           1      False               9  
..       ...      ...    ...         ...        ...             ...  
795      100      150     50           6       True             -50  
796      160      110    110           6       True              50  
797      150      130     70           6       True              50  
798      170      130     80           6       True             100  
799      130       90     70           6       True             -10  

[800 rows x 14 columns]

In [121]:
df['Sum of 4:10']=df.iloc[:,4:10].sum(axis=1)
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Sum of 4:10  
0         65       65     45           1      False          591  
1         80       80     60           1      False          750  
2        100      100     80           1      False          970  
3        122      120     80           1      False         1170  
4         60       50     65           1      False          553  
..       ...      ...    ...         ...        ...          ...  
795      100      150     50           6       True         1150  
796      160      110    110           6       True         1290  
797      150      130     70           6       True         1130  
798      170      130     80           6       True         1280  
799      130       90     70           6       True         1130  

[800 rows x 14 columns]

In [126]:
df['Attack lvl']=np.where(df['Attack']>50,'More than 50','Less than 50')

In [141]:
df

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary    Attack lvl  
0         65       65     45           1      False  Less than 50  
1         80       80     60           1      False  More than 50  
2        100      100     80           1      False  More than 50  
3        122      120     80           1      False  More than 50  
4         60       50     65           1      False  More than 50  
..       ...      ...    ...         ...        ...           ...  
795      100      150     50           6       True  More than 50  
796      160      110    110           6       True  More than 50  
797      150      130     70           6       True  More than 50  
798      170      130     80           6       True  More than 50  
799      130       90     70           6       True  More than 50  

[800 rows x 13 columns]

In [144]:
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']

In [145]:
df

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary    Attack lvl  Total  
0         65       65     45           1      False  Less than 50    318  
1         80       80     60           1      False  More than 50    405  
2        100      100     80           1      False  More than 50    525  
3        122      120     80           1      False  More than 50    625  
4         60       50     65           1      False  More than 50    309  
..       ...      ...    ...         ...        ...           ...    ...  
795      100      150     50           6       True  More than 50    600  
796      160      110    110           6       True  More than 50    700  
797      150      130     70           6       True  More than 50    600  
798      170      130     80           6       True  More than 50    680  
799      130       90     70           6       True  More than 50    600  

[800 rows x 14 columns]

In [7]:
df['Speed category']=df['Speed'].apply(lambda x: 'High' if x>=70 else 'Low')
df.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary Speed category  
0       65       65     45           1      False            Low  
1       80       80     60           1      False            Low  
2      100      100     80           1      False           High  
3      122      120     80           1      False           High  
4       60       50     65           1      False            Low

### How to rename a column

In [153]:
df.rename(columns={'Total':'Totals'}).head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary    Attack lvl  Totals  
0       65     45           1      False  Less than 50     318  
1       80     60           1      False  More than 50     405  
2      100     80           1      False  More than 50     525  
3      120     80           1      False  More than 50     625  
4       50     65           1      False  More than 50     309

### How to drop a column

In [122]:
df.drop(columns='Sum of 4:10',inplace=True)
df

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

### Aggregate funtions in Dataframes

In [39]:
dn=pd.read_csv('people.csv')
dn

Age  Gender   Hometown  Height  Qualification Smoker  weight
0    45    Male     Mumbai     167       Graduate    Yes      67
1    23  Female     Mumbai     170       Graduate     No      44
2    27    Male     Mumbai     175  Post-graduate     No      55
3    34    Male      Delhi     155       Graduate     No      28
4    43  Female     Mumbai     157  Post-graduate    Yes      77
5    34    Male      Delhi     167        Diploma    Yes      68
6    44  Female     Mumbai     165       Graduate    Yes      44
7    56  Female      Delhi     170        Diploma    Yes      66
8    34    Male      Delhi     175  Post-graduate     No      29
9    49  Female  Bangalore     162  Post-graduate    Yes      88
10   35    Male  Bangalore     160       Graduate     No      94
11   28  Female     Mumbai     165        Diploma     No      36
12   54    Male      Delhi     170        Diploma    Yes      55
13   59  Female     Mumbai     175       Graduate     No      77
14   54    Male  Bangalore     175        Diploma    Yes      44
15   43  Female     Mumbai     155  Post-graduate     No      77
16   56  Female     Mumbai     151       Graduate     No      88
17   41    Male  Bangalore     180        Diploma     No      44
18   56    Male      Delhi     182       Graduate    Yes      67
19   53    Male  Bangalore     156  Post-graduate    Yes      59
20   21  Female  Bangalore     158  Post-graduate     No      22

## How to count

#### How to count the values in it

In [41]:
dn['Hometown'].value_counts()

Hometown
Mumbai       9
Delhi        6
Bangalore    6
Name: count, dtype: int64

#### How to count the values after  filtering

In [45]:
dn[dn['Qualification']=='Graduate']['Hometown'].value_counts()

Hometown
Mumbai       5
Delhi        2
Bangalore    1
Name: count, dtype: int64

## How to group

In [47]:
grp=dn.groupby(by='Gender')['Age'].mean().to_frame()
grp

Age
Gender           
Female  42.200000
Male    42.454545

In [107]:
dn.groupby(by='Gender')['Age'].count().to_frame()

Age
Gender     
Female   10
Male     11

In [52]:
dn.groupby(by='Qualification').agg({'Age':'mean','Height':'mean'})

Age      Height
Qualification                       
Diploma        44.500000  171.166667
Graduate       44.000000  165.625000
Post-graduate  38.571429  162.571429

### How to concatenate two seeries

In [12]:
import pandas as pd

# Create two Series
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([4, 5, 6])

# Concatenate the Series
concatenated_series = pd.concat([series1, series2],axis=1)

print(concatenated_series)

   0  1
0  1  4
1  2  5
2  3  6


In [4]:
import pandas as pd
series1 = pd.Series([1, 2, 3])
series2 = pd.Series([4, 5, 6])
concatenated_series = pd.concat([series1, series2])
custom_index = ['a', 'b', 'c', 'd', 'e', 'f']
concatenated_series.index = custom_index

print(concatenated_series)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


### How to concatenate two Dataframees in python

In [15]:
df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

df2 = pd.DataFrame({
    'C': [7, 8, 9],
    'D': [10, 11, 12]
})

# Concatenate DataFrames along columns
concatenated_df = pd.concat([df1, df2], axis=1)

print(concatenated_df)

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12


### How to merge two Dataframes

In [16]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'location': ['New York', 'Los Angeles', 'Chicago']
})

df2 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'country': ['USA', 'USA', 'Canada']
})

In [19]:
df1.merge(df2,how='outer')

name  age     location country
0    Alice   25     New York     USA
1      Bob   30  Los Angeles     USA
2  Charlie   35      Chicago  Canada

In [55]:
data1 = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'age': [28, 34, 29, 40, 22],
    'location': ['New York', 'Los Angeles', 'Chicago', 'Miami', 'Seattle'],
    'email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 'david@example.com', 'eva@example.com']
}

data2 = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'James'],
    'age': [28, 34, 29, 40, 22],
    'country': ['USA', 'USA', 'USA', 'USA', 'USA'],
    'phone': ['123-456-7890', '234-567-8901', '345-678-9012', '456-789-0123', '567-890-1234']
}


df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)

df1.merge(df2,how='left',on='name')

name  age_x     location                email  age_y country  \
0    Alice     28     New York    alice@example.com   28.0     USA   
1      Bob     34  Los Angeles      bob@example.com   34.0     USA   
2  Charlie     29      Chicago  charlie@example.com   29.0     USA   
3    David     40        Miami    david@example.com   40.0     USA   
4      Eva     22      Seattle      eva@example.com    NaN     NaN   

          phone  
0  123-456-7890  
1  234-567-8901  
2  345-678-9012  
3  456-789-0123  
4           NaN

In [35]:
df1.merge(df2,how='outer',on=['age','name'])

name  age     location                email country         phone
0    Alice   28     New York    alice@example.com     USA  123-456-7890
1      Bob   34  Los Angeles      bob@example.com     USA  234-567-8901
2  Charlie   29      Chicago  charlie@example.com     USA  345-678-9012
3    David   40        Miami    david@example.com     USA  456-789-0123
4      Eva   22      Seattle      eva@example.com     NaN           NaN
5    James   22          NaN                  NaN     USA  567-890-1234

### Difference Between .join and .merge in Pandas DataFrames

.join
Primary focus: Joining DataFrames based on their indexes.
Default behavior: Left join (keeps all rows from the left DataFrame).
Less flexible: Limited control over join conditions.


.merge
More versatile: Combines DataFrames based on common columns or indexes.
Flexible: Offers various join types (inner, outer, left, right) and control over join conditions.
SQL-like: Similar to SQL joins.

### How to set Index

In [44]:
import pandas as pd

# Original DataFrame
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'location': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)

# Create a DataFrame with employee IDs
emp_ids = pd.DataFrame({
    'emp_id': [1, 2, 3]
})

# Add the employee IDs to the original DataFrame
df = pd.concat([emp_ids, df], axis=1)

# Set the 'emp_id' column as the index
df.set_index('emp_id', inplace=True)

# Display the updated DataFrame
df

name  age     location
emp_id                           
1         Alice   25     New York
2           Bob   30  Los Angeles
3       Charlie   35      Chicago

### How to handle Null values

In [36]:
df1.loc[2,'location']='New Jersy'

In [37]:
df1

name   age     location
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie   NaN    New Jersy

In [38]:
df1.fillna(df1['age'].mean())

name   age     location
0    Alice  25.0     New York
1      Bob  30.0  Los Angeles
2  Charlie  27.5    New Jersy

### How to use Pivot table in dataframes

A pivot table is a powerful data analysis tool that allows you to summarize and reorganize large datasets. It's similar to the pivot tables found in spreadsheet software like Excel.

In Pandas, you use the pivot_table() function to create pivot tables. This function takes a DataFrame as input and allows you to:

Group data by one or more columns (index and columns parameters).
Aggregate data using functions like sum, mean, count, etc. (aggfunc parameter).
Create a multi-level index or column structure.

In [58]:
import pandas as pd

# Create a simple DataFrame
data = {
    'Department': ['HR', 'Finance', 'IT', 'HR', 'IT', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 60000, 55000, 52000, 58000, 61000]
}

df = pd.DataFrame(data)

# Create a pivot table
pivot_table = pd.pivot_table(df, values='Salary', index='Department', aggfunc='mean')

print("Pivot Table:")
print(pivot_table)

Pivot Table:
             Salary
Department         
Finance     60500.0
HR          51000.0
IT          56500.0


In [67]:
pivot_table1=pd.pivot_table(df,values='Salary',index='Department',aggfunc='mean')
pivot_table1

Salary
Department         
Finance     60500.0
HR          51000.0
IT          56500.0

### What are cross tab

A cross table in Python is a way to summarize data based on two or more categorical variables. It's similar to the pivot tables you might use in Excel.

### Diff between Cross table and pivot table

Cross Table
Focus: Primarily used for categorical data.   
Functionality: Counts the frequency of occurrences for combinations of categorical variables.   
Simplicity: Generally simpler than pivot tables.


Pivot Table
Focus: Can be used for both categorical and numerical data.   
Functionality: Offers more flexibility in summarizing data, including calculations like sum, average, count, etc.   
Complexity: Can be more complex due to additional features and options.

### How to use cross table

In [49]:
import pandas as pd

# Create a simple DataFrame
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'Preference': ['Sports', 'Music', 'Music', 'Sports', 'Sports', 'Music']
}

df = pd.DataFrame(data)

# Create a cross-tabulation
crosstab = pd.crosstab(df['Gender'], df['Preference'])

print("Cross-Tabulation:")
print(crosstab)

Cross-Tabulation:
Preference  Music  Sports
Gender                   
Female          2       1
Male            1       2


### How to check duplicates in a dataframe

In [51]:
import pandas as pd

# Create a simple DataFrame with duplicate rows
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
    'Age': [25, 30, 35, 25, 30],
    'Location': ['New York', 'Los Angeles', 'Chicago', 'New York', 'Los Angeles']
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Check for duplicate rows
duplicates = df.duplicated()



# Display duplicate rows
print("\nDuplicate Rows:")
print(df[duplicates])

Original DataFrame:
      Name  Age     Location
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    Alice   25     New York
4      Bob   30  Los Angeles

Duplicate Rows:
    Name  Age     Location
3  Alice   25     New York
4    Bob   30  Los Angeles


### How to Replace Null Values

In [30]:
import pandas as pd
import numpy as np

# Sample DataFrame with null values
data = {'A': [1, 2,np.nan, 4],
        'B': [5,8,np.nan, 8],
        'C': [9, 10, 11,np.nan]}
df = pd.DataFrame(data)

# Replace all null values with 0
df_filled = df.fillna('No value')

print(df_filled)

          A         B         C
0       1.0       5.0       9.0
1       2.0       8.0      10.0
2  No value  No value      11.0
3       4.0       8.0  No value


array([1, 2, 3, 4, 5])